using System;
using XamlTest;

[assembly: GenerateHelpers(typeof(System.Windows.Controls.StickyNoteControl))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.AccessText))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.AdornedElementPlaceholder))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.Border))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.Button))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.Calendar))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.Canvas))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.CheckBox))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.ComboBox))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.ComboBoxItem))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.ContentControl))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.ContentPresenter))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.ContextMenu))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.Control))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.DataGrid))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.DataGridCell))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.DataGridCellsPanel))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.DataGridRow))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.DatePicker))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.Decorator))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.DockPanel))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.DocumentViewer))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.Expander))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.FlowDocumentReader))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.FlowDocumentScrollViewer))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.Frame))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.Grid))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.GridSplitter))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.GridViewColumnHeader))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.GridViewHeaderRowPresenter))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.GridViewRowPresenter))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.GroupBox))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.GroupItem))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.HeaderedContentControl))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.HeaderedItemsControl))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.Image))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.InkCanvas))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.InkPresenter))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.ItemsControl))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.ItemsPresenter))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.Label))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.ListBox))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.ListBoxItem))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.ListView))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.ListViewItem))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.MediaElement))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.Menu))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.MenuItem))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.Page))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.Panel))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.PasswordBox))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.ScrollContentPresenter))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.ProgressBar))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.RadioButton))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.RichTextBox))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.ScrollViewer))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.Separator))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.FlowDocumentPageViewer))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.Slider))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.StackPanel))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.TabControl))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.TabItem))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.TextBlock))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.TextBox))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.ToolBar))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.ToolBarTray))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.ToolTip))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.TreeView))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.TreeViewItem))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.UserControl))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.Viewbox))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.Viewport3D))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.VirtualizingPanel))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.VirtualizingStackPanel))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.WebBrowser))]
[assembly: GenerateHelpers(typeof(System.Windows.Controls.WrapPanel))]

namespace XamlTest
{
    [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true)]
    public class GenerateHelpersAttribute : Attribute
    {
        public Type ControlType { get; set; }

        public string? Namespace { get; set; }

        public GenerateHelpersAttribute(Type controlType)
        {
            ControlType = controlType;
        }
    }
}
