using System;
using XamlTest.Tests;

[assembly: GenerateTests(typeof(System.Windows.Window))]
[assembly: GenerateTests(typeof(System.Windows.Controls.AccessText))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Border))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Button))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Calendar))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Canvas))]
[assembly: GenerateTests(typeof(System.Windows.Controls.CheckBox))]
[assembly: GenerateTests(typeof(System.Windows.Controls.ComboBox))]
[assembly: GenerateTests(typeof(System.Windows.Controls.ComboBoxItem))]
[assembly: GenerateTests(typeof(System.Windows.Controls.ContentControl))]
[assembly: GenerateTests(typeof(System.Windows.Controls.ContentPresenter))]
[assembly: GenerateTests(typeof(System.Windows.Controls.ContextMenu))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Control))]
[assembly: GenerateTests(typeof(System.Windows.Controls.DataGrid))]
[assembly: GenerateTests(typeof(System.Windows.Controls.DataGridCell))]
[assembly: GenerateTests(typeof(System.Windows.Controls.DataGridCellsPanel))]
[assembly: GenerateTests(typeof(System.Windows.Controls.DataGridRow))]
[assembly: GenerateTests(typeof(System.Windows.Controls.DatePicker))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Decorator))]
[assembly: GenerateTests(typeof(System.Windows.Controls.DockPanel))]
[assembly: GenerateTests(typeof(System.Windows.Controls.DocumentViewer))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Expander))]
[assembly: GenerateTests(typeof(System.Windows.Controls.FlowDocumentReader))]
[assembly: GenerateTests(typeof(System.Windows.Controls.FlowDocumentScrollViewer))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Frame))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Grid))]
[assembly: GenerateTests(typeof(System.Windows.Controls.GridSplitter))]
[assembly: GenerateTests(typeof(System.Windows.Controls.GridViewColumnHeader))]
[assembly: GenerateTests(typeof(System.Windows.Controls.GridViewHeaderRowPresenter))]
[assembly: GenerateTests(typeof(System.Windows.Controls.GridViewRowPresenter))]
[assembly: GenerateTests(typeof(System.Windows.Controls.GroupBox))]
[assembly: GenerateTests(typeof(System.Windows.Controls.GroupItem))]
[assembly: GenerateTests(typeof(System.Windows.Controls.HeaderedContentControl))]
[assembly: GenerateTests(typeof(System.Windows.Controls.HeaderedItemsControl))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Image))]
[assembly: GenerateTests(typeof(System.Windows.Controls.InkCanvas))]
[assembly: GenerateTests(typeof(System.Windows.Controls.InkPresenter))]
[assembly: GenerateTests(typeof(System.Windows.Controls.ItemsControl))]
[assembly: GenerateTests(typeof(System.Windows.Controls.ItemsPresenter))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Label))]
[assembly: GenerateTests(typeof(System.Windows.Controls.ListBox))]
[assembly: GenerateTests(typeof(System.Windows.Controls.ListBoxItem))]
[assembly: GenerateTests(typeof(System.Windows.Controls.ListView))]
[assembly: GenerateTests(typeof(System.Windows.Controls.ListViewItem))]
[assembly: GenerateTests(typeof(System.Windows.Controls.MediaElement))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Menu))]
[assembly: GenerateTests(typeof(System.Windows.Controls.MenuItem))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Page))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Panel))]
[assembly: GenerateTests(typeof(System.Windows.Controls.PasswordBox))]
[assembly: GenerateTests(typeof(System.Windows.Controls.ScrollContentPresenter))]
[assembly: GenerateTests(typeof(System.Windows.Controls.ProgressBar))]
[assembly: GenerateTests(typeof(System.Windows.Controls.RadioButton))]
[assembly: GenerateTests(typeof(System.Windows.Controls.RichTextBox))]
[assembly: GenerateTests(typeof(System.Windows.Controls.ScrollViewer))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Separator))]
[assembly: GenerateTests(typeof(System.Windows.Controls.FlowDocumentPageViewer))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Slider))]
[assembly: GenerateTests(typeof(System.Windows.Controls.StackPanel))]
[assembly: GenerateTests(typeof(System.Windows.Controls.TabControl))]
[assembly: GenerateTests(typeof(System.Windows.Controls.TabItem))]
[assembly: GenerateTests(typeof(System.Windows.Controls.TextBlock))]
[assembly: GenerateTests(typeof(System.Windows.Controls.TextBox))]
[assembly: GenerateTests(typeof(System.Windows.Controls.ToolBar))]
[assembly: GenerateTests(typeof(System.Windows.Controls.ToolBarTray))]
[assembly: GenerateTests(typeof(System.Windows.Controls.ToolTip))]
[assembly: GenerateTests(typeof(System.Windows.Controls.TreeView))]
[assembly: GenerateTests(typeof(System.Windows.Controls.TreeViewItem))]
[assembly: GenerateTests(typeof(System.Windows.Controls.UserControl))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Viewbox))]
[assembly: GenerateTests(typeof(System.Windows.Controls.VirtualizingPanel))]
[assembly: GenerateTests(typeof(System.Windows.Controls.VirtualizingStackPanel))]
[assembly: GenerateTests(typeof(System.Windows.Controls.WebBrowser))]
[assembly: GenerateTests(typeof(System.Windows.Controls.WrapPanel))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.BulletDecorator))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.ButtonBase))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.CalendarButton))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.CalendarDayButton))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.CalendarItem))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.CustomPopupPlacement))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.CustomPopupPlacementCallback))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.DataGridCellsPresenter))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.DataGridColumnHeader))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.DataGridColumnHeadersPresenter))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.DataGridDetailsPresenter))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.DataGridRowHeader))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.DataGridRowsPresenter))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.DatePickerTextBox))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.DocumentPageView))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.DocumentViewerBase))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.DragCompletedEventHandler))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.DragDeltaEventHandler))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.DragStartedEventHandler))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.GridViewRowPresenterBase))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.ItemsChangedEventHandler))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.LayoutInformation))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.MenuBase))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.MultiSelector))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.Popup))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.RangeBase))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.RepeatButton))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.ResizeGrip))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.ScrollBar))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.ScrollEventHandler))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.SelectiveScrollingGrid))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.Selector))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.StatusBar))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.StatusBarItem))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.TabPanel))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.TextBoxBase))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.Thumb))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.TickBar))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.ToggleButton))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.ToolBarOverflowPanel))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.ToolBarPanel))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.Track))]
[assembly: GenerateTests(typeof(System.Windows.Controls.Primitives.UniformGrid))]

namespace XamlTest.Tests;

[AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true)]
public class GenerateTestsAttribute : Attribute
{
    public Type ControlType { get; set; }

    public GenerateTestsAttribute(Type controlType)
    {
        ControlType = controlType;
    }
}
